site_name: Prefeitura de Londrina
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Prefeitura-de-Londrina 
repo_name: 2021.1-Prefeitura-de-Londrina

theme:
  name: "material"
  lang:
    - pt
  palette:
    primary: green
  logo: assets/img/brasao_londrina.jpg
  favicon: assets/img/brasao_londrina.jpg
  palette:
    primary: black
    accent: blue

nav:
  - Inicio: index.md
  - Planejamento: planejamento/planejamento.md
  - Processo de Design: processo_design/processo-de-design.md
  - Analise de Requisitos: 
    - Análise de tarefas:
      - CMN GOMS: analise_de_requisitos/analise_de_tarefas/cmn_goms.md
      - CTT: analise_de_requisitos/analise_de_tarefas/ctt.md
      - HTA: analise_de_requisitos/analise_de_tarefas/hta.md
      - KLM: analise_de_requisitos/analise_de_tarefas/klm.md
    - Perfil do usuário:
      - Personas: analise_de_requisitos/analise_de_tarefas/personas.md
    - Princípios de Projeto: analise_de_requisitos/principios_de_projeto.md
    - Guia de Estilo: analise_de_requisitos/guia_de_estilo.md
    - Metas de usabilidade: analise_de_requisitos/metas.md
  - Design, avaliação e desenvolvimento:
    - Nível 1:
      - Analise de tarefas:
        - Planejamento: avaliacao_desenvolvimento/planejamento.md
        - Entrevista: avaliacao_desenvolvimento/entrevista.md
        - Avaliação: avaliacao_desenvolvimento/avaliacao.md
      - Storyboards: 
        - Storyboards: atividades_design/storyboards/storyboards.md
        - Planejamento da Avaliação: atividades_design/storyboards/planejamento_avaliacao.md
        - Relato dos Resultados: atividades_design/storyboards/relato_dos_resultados.md
    - Nível 2:
      - Protótipo de papel:
        - Planejamento protótipo de Papel: prototipo_de_papel/planejamento.md
        - Relato dos resultados da avaliação do protótipo de Papel: prototipo_de_papel/relato-dos-resultados.md
        - Protótipo: prototipo_de_papel/prototipoBaixa.md
        - Assinaturas:
            - Andre Maciel: prototipo_de_papel/assinaturas/andre_maciel.md
            - Julia Rataieski: prototipo_de_papel/assinaturas/julia_rataieski.md
    - Nivel 3:
      - Protótipo de alta fidelidade:
          - Planejamento da Avaliação Prototipo de Alta Fidelidade: atividades_design/prototipo_alta/planejamento_avaliacao.md
          - Resultados da Avaliação Prototipo de Alta Fidelidade: atividades_design/prototipo_alta/resultados_avaliacao.md
          - Protótipo: atividades_design/prototipo_alta/prototipoAlta.md
          - Assinaturas:
            - Antônio Rangel: atividades_design/prototipo_alta/assinaturas/antonio_rangel.md
            - Kess Jhones: atividades_design/prototipo_alta/assinaturas/kess_jhones.md
  - Verificações: 
    - Verificações gerais do site: verificacao_dos_artefatos/verificacoes_gerais.md
    - Personas: verificacao_dos_artefatos/personas.md
    - Entrevista: verificacao_dos_artefatos/entrevista.md
    - Princípios de Projeto: verificacao_dos_artefatos/principios.md
    - Metas de Usabilidade: verificacao_dos_artefatos/metas_de_usabilidade.md
    - Guia de Estilo: verificacao_dos_artefatos/guia_de_estilo.md
    - Análise de Tarefas: verificacao_dos_artefatos/analise_de_tarefas.md
    - Planejamento e Avaliação da Análise de Tarefas: verificacao_dos_artefatos/planejamento_e_avalicao_AT.md
    - Storyboards: verificacao_dos_artefatos/storyboards.md
    - Planejamento e Avaliação dos Storyboards: verificacao_dos_artefatos/planejamento_e_avaliacao_storyboards.md
    - Protótipo de Papel: verificacao_dos_artefatos/prototipo_papel.md
    - Planejameno e Avaliação do Protótipo de Papel: verificacao_dos_artefatos/planejamento_e_avalicao_PP.md
    - Protótipo de Alta-Fidelidade: verificacao_dos_artefatos/prototipo_de_alta_fidelidade.md
    - Planejamento e Avaliação do Protótipo de Alta-Fidelidade: verificacao_dos_artefatos/planejamento_e_avalicao_PA.md
  - Apresentações: 
    - Apresentação 1: apresentacao/apresentacao1.md
    - Apresentaçao 2: apresentacao/apresentacao2.md
    - Apresentaçao 3: apresentacao/apresentacao3.md
    - Apresentaçao 4: apresentacao/apresentacao4.md
    - Apresentaçao 5: apresentacao/apresentacao5.md
    - Apresentaçao 6: apresentacao/apresentacao6.md
    - Apresentaçao 7: apresentacao/apresentacao7.md
    - Apresentaçao Final: apresentacao/apresentacaoFinal.md

plugins:
  - search
