site_name: Prefeitura de Londrina
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Prefeitura-de-Londrina 

theme:
  name: "material"
  lang:
    - pt
  palette:
    primary: green
  features:
    - navigation.tabs
  logo: assets/img/brasao_londrina.jpg
  favicon: assets/img/brasao_londrina.jpg
  palette:
    primary: black
    accent: blue

nav:
  - Inicio: index.md
  - Planejamento: planejamento/planejamento.md
  - Processo de Design: processo_design/processo-de-design.md
  - Apresentações: 
    - Apresentação 1: apresentacao/apresentacao1.md
  - Análise de tarefas:
    - CPM GOMS: analise_de_tarefas/cpm_goms.md
<<<<<<< HEAD
    - KLM: analise_de_tarefas/klm.md
=======
    - Personas: analise_de_tarefas/personas.md
>>>>>>> 8ddfc18d2c0a90f34705de7bdb6e83352ab5f8e3

plugins:
  - search

