site_name: Prefeitura de Londrina
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Prefeitura-de-Londrina 

theme:
  name: "material"
  lang:
    - pt
  palette:
    primary: green
  features:
    - navigation.tabs
  logo: assets/img/brasao_londrina.jpg
  favicon: assets/img/brasao_londrina.jpg
  palette:
    primary: black
    accent: blue

nav:
  - Inicio: index.md
  - Planejamento: planejamento/planejamento.md
  - Processo de Design: processo_design/processo-de-design.md
  - Analise de Requisitos: 
    - Análise de tarefas:
      - CMN GOMS: analise_de_requisitos/analise_de_tarefas/cmn_goms.md
      - CPM GOMS: analise_de_requisitos/analise_de_tarefas/cpm_goms.md
      - CTT: analise_de_requisitos/analise_de_tarefas/ctt.md
      - HTA: analise_de_requisitos/analise_de_tarefas/hta.md
      - KLM: analise_de_requisitos/analise_de_tarefas/klm.md
    - Perfil do usuário:
      - Personas: analise_de_requisitos/analise_de_tarefas/personas.md
    - Princípios de Projeto: analise_de_requisitos/principios_de_projeto.md
    - Guia de Estilo: analise_de_requisitos/guia_de_estilo.md
    - Metas de usabilidade: analise_de_requisitos/metas.md
  - Apresentações: 
    - Apresentação 1: apresentacao/apresentacao1.md
    - Apresentaçao 2: apresentacao/apresentacao2.md
    - Apresentaçao 3: apresentacao/apresentacao3.md

plugins:
  - search

