site_name: Grupo 06

theme:
  name: "material"
  lang:
    - pt
  palette:
    primary: green
  features:
    - navigation.tabs

plugins:
  - search

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js
